### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Irostovsky** [ThomasGeorgiadisIO/test_code_task_python_django_engineer#1]
Hi @ThomasGeorgiadisIO 
I m Ivan, from GuestReady.
Thanks for the doing the task. 
I have couple notes:
1. What was the reason to ue the template tag to get the previous reservation?https://github.com/ThomasGeorgiadisIO/test_code_task_python_django_engineer/blob/9e0439844c9206cd8b582191a28146b2a7e3b27f/test_task_project/booking_app/templates/booking_app/reservation_list.html#L23
2. In the filter https://github.com/ThomasGeorgiadisIO/test_code_task_python_django_engineer/blob/main/test_task_project/booking_app/templatetags/custom_filter.py#L12 the code does the SQL request for every reservation in loop. Is it possible to optimize the code to decrease the count of SQL requests for this view?
3. Small one, but curios, why the Rental FK is named `rental_id`? https://github.com/ThomasGeorgiadisIO/test_code_task_python_django_engineer/blob/main/test_task_project/booking_app/models.py#L9 Is it django way?

Waiting for your response.

**Comment by ThomasGeorgiadisIO** [comment]
Hi @Irostovsky,
my thoughts:

1. Reuseability of the filter across the app. I tried overriding the queryset of the class view and use the "annotate" method, but I couldn't approach the problem in a way that allowed me to retrieve the previous entry based on each query object's checkin date dynamically.

2. You are right, this approach does execute the sql request in each loop. I have instead changed the filter a little bit, so it is now applied once to the whole list, instead of each record separately. I also changed the tests. Please take a look at the updated code.

3. You are right, the FK should be named rental, which points to a rental object and not its id.

Please let me know if you have any other comments/suggestions.
Thank you for your time.

**Comment by Irostovsky** [comment]
Hi @ThomasGeorgiadisIO 
Thanks for the updates.
I m not sure the template tag is a place to do a requests to prepare data, but in your version you do a real filtering. So okish.
Two things are not supported now:
1. In real life the reservations are created not sequentially. Ie reservation June 13-15 could be created first, then the reservation May 10-23. So default ordering does not work.
2. You do the calculation on the python level, ie the looping into filter method. But as you know the speed of python operations are much slower then the same into database level. 

So could you rewrite the way you calculate the previous reservation to avoid looping on python level?

**Comment by ThomasGeorgiadisIO** [comment]
Hi @Irostovsky 

1. Data come ordered in object_list by the ListView by rental, checkin. In order to imitate the real life senario I populated the database with no sequential reservations from the beginning to showcase:
![image](https://user-images.githubusercontent.com/93729220/170669572-a487de1c-c32b-44df-8698-0373b3b83f3c.png)

2. According to the instructions I was convinced that models.py is not to be touched. Since annotation of a queryset with a queryset or sub is not possible and to avoid any looping in python, as well as avoid multiple calls to the database(1st review), I have to ask if altering models.py is permitted to achieve the task by having a column of previous reservations. Upon confirmation I shall proceed.

**Comment by Irostovsky** [comment]
Hi @ThomasGeorgiadisIO 
Agree about ordering. My bad, I did not mention the ordering attribute of the view.

About using python loop to get the previous reservation. Why do you think you can’t use the annotation, etc querysets operation? I don’t remember this limitation. 
Also, the one downside of the python loop is a pagination. Imagine you show the items 10-20 from the 100 items. Then the previous reservation could not be into the looped list but in 0-10 list.
So, it is one more reason to try another way to calculate the previous reservation.

**Comment by ThomasGeorgiadisIO** [comment]
Hi @Irostovsky 
The only limitation was my knowledge. I had to figure out how to dynamically pass parameters in the subquery or rawsql from current query object. Have used annotate before with simple query with Count, Avg, Min, Max. OutRef is the answer. So I removed the filter, override queryset to annotate the previous reservation id and alter tests. 
Thank you for your time.

**Comment by ThomasGeorgiadisIO** [comment]
Please ignore my last commit. I just changed the name of the subquery. The previous commit has the changes. I am looking forward for your review.

**Comment by Irostovsky** [comment]
@ThomasGeorgiadisIO yes, the Subquery is one of the possible solutions. Accepted.

But one more small case I would ask you to resolve before going forward.  Could you check that only one request to database is executed on the view?

**Comment by ThomasGeorgiadisIO** [comment]
Hi @Irostovsky
After installing debug_toolbar, I realized that the database was called for every object to locate object.rental.name
![image](https://user-images.githubusercontent.com/93729220/170850442-b84bf791-427b-471b-8e84-c99079c5c9fb.png)
Adding prefetch_related('rental') resolves this issue(https://github.com/ThomasGeorgiadisIO/test_code_task_python_django_engineer/commit/841a3022c6fc019d762e14394fe14d66f823f62a):
![image](https://user-images.githubusercontent.com/93729220/170850553-153ee999-c15a-4e40-be26-809d6b22da9b.png)
Sorry for replying on a Sunday morning. Have a nice week.

**Comment by Irostovsky** [comment]
Perfect! @ThomasGeorgiadisIO 
See you on the screen interview.
